# Generated by Django 3.0.5 on 2020-04-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(default=None)),
            ],
            options={
                'db_table': 'summaries',
            },
        ),
    ]
